[build]
target = "riscv32imafc-esp-espidf"

[target.riscv32imafc-esp-espidf]
linker = "ldproxy"
runner = "scripts/cargo-runner.sh"
rustflags = [
    "--cfg", "espidf_time64",
]

[unstable]
build-std = ["std", "panic_abort"]

[env]
MCU = "esp32p4"
CC_riscv32imafc_esp_espidf = { value = "scripts/riscv32-cc.sh", relative = true }
AR_riscv32imafc_esp_espidf = { value = ".embuild/espressif/tools/riscv32-esp-elf/esp-14.2.0_20251107/riscv32-esp-elf/bin/riscv32-esp-elf-ar", relative = true }
LIBCSP_BUFFER_SIZE = "600"
BINDGEN_EXTRA_CLANG_ARGS_riscv32imafc_esp_espidf = "-I/Users/tk/user/dev/beacon/.embuild/espressif/tools/riscv32-esp-elf/esp-14.2.0_20251107/riscv32-esp-elf/riscv32-esp-elf/include"
ESP_IDF_VERSION = "v5.5.3"
ESP_IDF_TOOLS_INSTALL_DIR = "workspace"
IDF_PATH = { value = ".embuild/espressif/esp-idf/v5.5.3", relative = true, force = true }
IDF_PYTHON_ENV_PATH = { value = ".embuild/espressif/python_env/idf5.5_py3.13_env", relative = true, force = true }
ESP_IDF_GLOB_0_BASE = { value = "cmake_override", relative = true }
ESP_IDF_GLOB_0_GLOB = "main/CMakeLists.txt"
